### PR TITLE
workaround serde deserializing incorrectly when arbitrary_precision enabled

### LINKED ISSUE #520: [jsonrpc-client-transports] jsonrpc does not deserialize if user has "arbitrary_precision" enabled in serde
If user is using `serde` with `features = ["arbitrary_precision"]` then jsonrpc errors:

```
ParseError("data did not match any variant of untagged enum ClientResponse", Error("data did not match any variant of untagged enum ClientResponse", line: 0, column: 0))
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Rpc(Other(Canceled))', src/libcore/result.rs:1187:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Related to: https://github.com/serde-rs/json/issues/505

jsonrpc deserializes into ClientResponse -> Output which are both `#[serde(untagged)]` enums

### PR DESCRIPTION
**Pull request by insipx**
serde deserializes incorrectly when arbitrary precision is enabled.

fixes #520 

The workaround is to deserialize into `Value` before `ClientResponse`. This is gated under the feature `arbitrary_precision` in core-client and `transports`.

### CODE REVIEW

**Comment by insipx** [comment]
there is now a generic fn `serde_from_str` which checks for `cfg!(feature = "arbitrary_precision")`.

Also made sure that cargo test --feature arbitrary_precision works

File: core-client/transports/src/transports/mod.rs [hunk 1]
```diff
@@ -81,7 +81,7 @@ impl RequestBuilder {
 pub fn parse_response(
 	response: &str,
 ) -> Result<(Id, Result<Value, RpcError>, Option<String>, Option<SubscriptionId>), RpcError> {
-	serde_json::from_str::<ClientResponse>(&response)
+	jsonrpc_core::serde_from_str::<ClientResponse>(response)
```
Comment (tomusdrw) [inline core-client/transports/src/transports/mod.rs]: Can we now get rid of `serde_json` dependency?

File: core/src/lib.rs [hunk 2]
```diff
@@ -54,3 +54,20 @@ pub use crate::io::{
 };
 pub use crate::middleware::{Middleware, Noop as NoopMiddleware};
 pub use crate::types::*;
+
+use serde_json::Error as SerdeError;
+
+/// workaround for https://github.com/serde-rs/json/issues/505
+/// Arbitrary precision confuses serde when deserializing into untagged enums,
+/// this is a workaround
+pub fn serde_from_str<'a, T>(input: &'a str) -> ::std::result::Result<T, SerdeError>
```
Comment (tomusdrw) [inline core/src/lib.rs]:
```suggestion
pub fn serde_from_str<'a, T>(input: &'a str) -> std::result::Result<T, SerdeError>
```

File: core-client/transports/src/transports/mod.rs (hunk 1 above)
Comment (insipx) [reply core-client/transports/src/transports/mod.rs]: `serde_json` is still used for all `to_string` serializations
