### PR TITLE
Don't process invalid CORS requests

### LINKED ISSUE #62: Don't process requests when invalid cross-origin request is received
Currently http and minihttp servers are processing the request even if `Origin` header is not allowed to access. The requester will not be able to read the response, but can cause side effects to happen on the node.
We should rather fail fast in such case and avoid even processing the request.

### PR DESCRIPTION
**Pull request by tomusdrw**
Closes #62 

Also returns correct headers for OPTIONS requests.

### CODE REVIEW

File: http/src/request_response.rs [hunk 1]
```diff
@@ -81,6 +85,16 @@ impl Response {
 			write_pos: 0,
 		}
 	}
+
+	/// CORS invalid
+	pub fn invalid_cors() -> Self {
+		Response {
+			code: StatusCode::Forbidden,
+			content_type: header::ContentType::html(),
```
Comment (maciejhirsz) [inline http/src/request_response.rs]: `ContentType::plaintext()` would match `invalid_cors` from minihttp.

**Comment by tomusdrw** [comment]
Beta and Nightly failures are not related no this PR and look like compiler regressions.
