### PR TITLE
Fix threading and closing of servers

### LINKED ISSUE #425: Somehow the server always spawn at least 2 threads.
If I don't mention the amount of threads or if I put `.threads(1)` I still see that there are 2 different threads operating.
Example code:

```
use jsonrpc_http_server::jsonrpc_core::*;
use jsonrpc_http_server::*;
use std::thread::{self, current, JoinHandle};

use jsonrpc_client_http::HttpTransport;
use jsonrpc_client_core::{jsonrpc_client, expand_params};


fn main() {
    let server = launch_server();
    thread::sleep(std::time::Duration::from_secs(5));

    let handles = send_requests(10);
    let results: Vec<_> = handles.into_iter().map(|h|h.join().unwrap()).collect();
    println!("{:?}", results);


}

fn launch_server() -> Server {
    let mut io = IoHandler::new();
    io.add_method("say_hello", |_: Params| {
        println!("I'm in thread ID: {:?}, name: {:?}", current().id(), current().name());
        Ok(Value::String("hello".to_string()))
    });

    let server = ServerBuilder::new(io)
        .threads(1)
        .start_http(&"127.0.0.1:3030".parse().unwrap())
        .unwrap();
    server
}



jsonrpc_client!(pub struct KeyManagementClient {
    pub fn say_hello(&mut self) -> RpcRequest<Value>;
});

fn send_requests(n: usize) -> Vec<JoinHandle<Value>> {
    let mut handles = Vec::with_capacity(n);
    for _ in 0..n {
        let handle = thread::spawn( || {
            let transport = HttpTransport::new().standalone().unwrap();
            let transport_handle = transport.handle("http://127.0.0.1:3030").unwrap();
            let mut client = KeyManagementClient::new(transport_handle);
            client.say_hello().call().unwrap()
        });
        handles.push(handle);
    }
    handles
}

```

Output:

```
I'm in thread ID: ThreadId(2), name: Some("jsonrpc-eventloop-0")
I'm in thread ID: ThreadId(3), name: Some("jsonrpc-eventloop-1")
I'm in thread ID: ThreadId(2), name: Some("jsonrpc-eventloop-0")
I'm in thread ID: ThreadId(3), name: Some("jsonrpc-eventloop-1")
I'm in thread ID: ThreadId(3), name: Some("jsonrpc-eventloop-1")
I'm in thread ID: ThreadId(2), name: Some("jsonrpc-eventloop-0")
I'm in thread ID: ThreadId(3), name: Some("jsonrpc-eventloop-1")
I'm in thread ID: ThreadId(2), name: Some("jsonrpc-eventloop-0")
I'm in thread ID: ThreadId(3), name: Some("jsonrpc-eventloop-1")
I'm in thread ID: ThreadId(2), name: Some("jsonrpc-eventloop-0")
[String("hello"), String("hello"), String("hello"), String("hello"), String("hello"), String("hello"), String("hello"), String("hello"), String("hello"), String("hello")]
```

As You can see there's threadID 2 and 3, (`jsonrpc-eventloop-0` and `jsonrpc-eventloop-1`) both operate within the code of the server.

cc https://github.com/paritytech/jsonrpc/issues/423 @tomusdrw

### PR DESCRIPTION
**Pull request by tomusdrw**
This PRs attempts to clean up the spawned threads (Closes #425).
Currently every `RpcEventLoop` spawns a bunch of threads that depend on the number of cores (tokio runtime) + one thread that waits for the runtime to complete. Instead we just spawn `tokio::runtime` with one thread and a right name.

Also we avoid calling `tokio::spawn` when handling incoming connections in various server implementations to ensure that when the server is closed all connections are dropped as well (currently, they are still being polled by the runtime so you have to wait for them to close or timeout).

### CODE REVIEW

**Comment by tomusdrw** [comment]
@ordian good point, let me try to come up with something.

**Comment by dvdplm** [comment]
Not sure exactly what change causes this but when `parity-ethereum` shuts down, this is printed:

```
^C2019-10-04 16:25:21  main INFO parity_ethereum::run  Finishing work, please wait...
2019-10-04 16:25:21  http.worker00 WARN jsonrpc_server_utils::suspendable_stream  Error accepting connection: reactor gone
2019-10-04 16:25:21  http.worker00 WARN jsonrpc_server_utils::suspendable_stream  The server will stop accepting connections for 20ms
```

Not a big deal but maybe we can dial [it down from](https://github.com/paritytech/jsonrpc/blob/31ec6d67f2ab338a26f5080af5804960f7ab39e4/server-utils/src/suspendable_stream.rs#L77-L78) `warn` to `debug`?

File: http/examples/http_async.rs [hunk 1]
```diff
@@ -9,6 +9,7 @@ fn main() {
 
 	let server = ServerBuilder::new(io)
 		.cors(DomainsValidation::AllowOnly(vec![AccessControlAllowOrigin::Null]))
+		.threads(8)
```
Comment (dvdplm) [inline http/examples/http_async.rs]:
```suggestion
		.threads(4)
```
Maybe a saner default?

Comment (tomusdrw) [reply http/examples/http_async.rs]: Removed this altogether, pushed by mistake :)

**Comment by tomusdrw** [comment]
@ordian @dvdplm Added a test that fails on `master` (the main issue is actually in dropping `IoHandler` not the server itself) and some docs to `reactor` module and `ServerBuilder::threads` method.

File: http/src/tests.rs [hunk 2]
```diff
@@ -1495,6 +1495,39 @@ fn should_respond_with_close_even_if_client_wants_to_keep_alive() {
...
+	};
+
+	// then
+	for _ in 1..1000 {
+		if weak.upgrade().is_none() {
+			return;
+		}
+		std::thread::sleep(std::time::Duration::from_millis(10));
+	}
+	assert!(false);
```
Comment (dvdplm) [inline http/src/tests.rs]:
```suggestion
	assert!(false, "expected server to be closed");
```

**Comment by dvdplm** [comment]
Travis failure seems spurious (restarted) but appveyor is perhaps legit?

File: http/src/tests.rs (hunk 2 above)
Comment (bkchr) [reply http/src/tests.rs]: Why not panic directly?

**Comment by ordian** [comment]
Let's merge this?

**Comment by dvdplm** [comment]
> Let's merge this?

I think we should sort out the Travis failures first.

**Comment by ordian** [comment]
@dvdplm I though it was spurious, can you confirm the test fails on macOS?

**Comment by dvdplm** [comment]
I have one failing test in `jsonrpc-derive`. Is that only osx though? @ordian/@todr can you try too please?

**Comment by ordian** [comment]
`cargo test --all` passes on my linux machine

**Comment by tomusdrw** [comment]
All good here as well. I just restarted the failing `unix/beta` build. But I think it should be good to go, all the previous failures where spurious.

**Comment by tomusdrw** [comment]
Oh, actually it depends on the rust compiler version. Just bumped my compiler to 1.38 and seeing issues with `compile_test` test.
